version: '3'
services:
  vue_demo_web:
    build:
      context: .
      dockerfile: ./web.docker
    container_name: vue_demo_web
    volumes:
      - ../:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8084:80
    links:
      - vue_demo_app
  vue_demo_app:
    build:
      context: .
      dockerfile: ./app.docker
    container_name: vue_demo_app
    volumes:
      - ../:/var/www
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
      - vue_demo_db
  vue_demo_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "33066:3306"
    volumes:
      - ./data/mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
